version: "3"
services:
    web:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - db
        environment:
            DatabaseServer: "db"
            DatabaseName: "mydb"
            DatabaseUser: "sa"
            DatabaseUserPassword: "Password1!"
    db:
        image: "microsoft/mssql-server-linux"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Password1!"
            ACCEPT_EULA: "Y"